### ISSUE TITLE
Preflight checklist

### ISSUE THREAD

**Issue by shadyabhi** [shadyabhi/jqtop#1]
- [x] Better readme explaining why/how of this tool. 
- [x] Better coverage for critical code-paths. (errors mostly).
- [x] Godoc should look pretty.

Once this is complete, we can release first version.

**Comment by shadyabhi** [comment]
This is done
